import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav
          style={{ background: "#0094d4" }}
          className="w-full text-foreground py-2 overflow-hidden relative flex items-center justify-center"
        >
          <div className="whitespace-nowrap animate-marquee font-bold text-lg text-center">
            Vote for Harkirat Kaur &nbsp; Vote for Harkirat Kaur &nbsp; Vote for
            Harkirat Kaur &nbsp; Vote for Harkirat Kaur &nbsp; Vote for Harkirat
            Kaur &nbsp; Vote for Harkirat Kaur &nbsp; Vote for Harkirat Kaur
            &nbsp; Vote for Harkirat Kaur &nbsp; Vote for Harkirat Kaur &nbsp;
            Vote for Harkirat Kaur &nbsp; Vote for Harkirat Kaur &nbsp; Vote for
            Harkirat Kaur &nbsp; Vote for Harkirat Kaur &nbsp; Vote for Harkirat
            Kaur &nbsp; Vote for Harkirat Kaur &nbsp; Vote for Harkirat Kaur
            &nbsp; Vote for Harkirat Kaur &nbsp; Vote for Harkirat Kaur &nbsp;
            Vote for Harkirat Kaur &nbsp; Vote for Harkirat Kaur &nbsp; Vote for
            Harkirat Kaur &nbsp; Vote for Harkirat Kaur &nbsp; Vote for Harkirat
            Kaur &nbsp; Vote for Harkirat Kaur
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
